### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by wang-qingqing** [liuxing/koa2-starter-cli#1]
I have a colleague  with the same name of you,
Did you know him?

**Comment by shengyur** [comment]
Me too.
Did you know him?

**Comment by zhaofeihao** [comment]
不好意思，我乱了。

**Comment by YC-1123** [comment]
OH MY GOD ~ is he our little doggie?

**Comment by du1wu2lzlz** [comment]
Maybe it’s a coincidence ， but u r really awesome

**Comment by liuxing** [comment]
和我同名吗？

WangQingqing <notifications@github.com> 于2018年7月5日周四 上午11:27写道：
